// vue-frontend/src/components/TaskTable.vue
<template>
  <div>
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h1 class="mb-0">Lista de Tareas</h1>
      <Button
        label="Crear nueva tarea"
        icon="pi pi-plus"
        class="p-button-primary"
        @click="abrirModalCreacion"
        raised
      />
    </div>

    <div class="mb-3 flex justify-content-between align-items-center">
      <InputText v-model="filtro" placeholder="Buscar tarea" class="w-50" />
    </div>

    <DataTable
      :value="tareasFiltradas"
      :paginator="true"
      :rows="5"
      :rowsPerPageOptions="[5, 10, 20]"
      paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
      responsiveLayout="scroll"
    >
      <Column field="title" header="Título" :sortable="true"></Column>
      <Column field="description" header="Descripción" :sortable="true"></Column>
      <Column field="createdAt" header="Fecha de alta" :sortable="true"></Column>
      <Column field="updatedAt" header="Fecha de actualización" :sortable="true"></Column>
      <Column field="completed" header="Estado" :sortable="true">
        <template #body="slotProps">
          <Tag
            :value="slotProps.data.completed ? 'Completada' : 'Pendiente'"
            :severity="slotProps.data.completed ? 'success' : 'danger'"
          />
        </template>
      </Column>
      <Column header="Acciones" :exportable="false" style="min-width: 8rem">
        <template #body="slotProps">
          <Button
            icon="pi pi-pencil"
            class="p-button-rounded p-button-success mx-2"
            @click="abrirModalEdicion(slotProps.data)"
          />
          <Button
            icon="pi pi-trash"
            class="p-button-rounded p-button-danger mx-2"
            @click="confirmarEliminar(slotProps.data)"
          />
          <Button
            :icon="slotProps.data.completed ? 'pi pi-times' : 'pi pi-check'"
            :class="slotProps.data.completed ? 'p-button-rounded p-button-warning mx-2' : 'p-button-rounded p-button-success mx-2'"
            @click="cambiarEstadoTarea(slotProps.data)"
            :title="slotProps.data.completed ? 'Marcar como pendiente' : 'Marcar como completada'"
          />
        </template>
      </Column>
    </DataTable>

    <!-- Diálogo para confirmar eliminación -->
    <Dialog
      v-model:visible="displayDeleteDialog"
      :style="{ width: '450px' }"
      header="Confirmar eliminación"
      :modal="true"
    >
      <div class="confirmation-content">
        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
        <span>¿Estás seguro de que quieres eliminar la tarea <b>{{ tareaSeleccionada?.title }}</b>?</span>
      </div>
      <template #footer>
        <Button
          label="Cancelar"
          icon="pi pi-times"
          @click="displayDeleteDialog = false"
          class="p-button-text"
        />
        <Button
          label="Eliminar"
          icon="pi pi-trash"
          @click="eliminarTarea"
          class="p-button-danger"
          :loading="loading"
        />
      </template>
    </Dialog>

    <!-- Diálogo para crear/editar tarea -->
    <Dialog
      v-model:visible="displayTaskDialog"
      :style="{ width: '370px' }"
      :header="modalTitle"
      :modal="true"
    >
      <div class="p-fluid">
        <div class="field">
          <div class="row">
            <div class="col-12">
              <div class="d-flex-column gap-2">
                <label for="titulo">Título</label><br>
                <InputText
                  id="titulo"
                  v-model="tareaForm.title"
                  required
                  autofocus
                  :class="{ 'p-invalid': submitted && !tareaForm.title }"
                />
                <small class="p-error" v-if="submitted && !tareaForm.title">
                  El título es requerido
                </small>
              </div>
            </div>
            <div class="col-12">
              <div class="field">
                <label for="descripcion">Descripción</label><br>
                <Textarea
                  id="descripcion"
                  v-model="tareaForm.description"
                  rows="5"
                  autoResize
                  class="w-full"
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <template #footer>
        <Button
          label="Cancelar"
          icon="pi pi-times"
          @click="cerrarDialogoTarea"
          class="p-button-text"
        />
        <Button
          :label="isEditing ? 'Actualizar' : 'Guardar'"
          icon="pi pi-check"
          @click="guardarTarea"
          class="p-button-primary"
          :loading="loading"
        />
      </template>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from "vue";
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import Textarea from "primevue/textarea";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import Tag from "primevue/tag";
import Dialog from "primevue/dialog";
import { toast } from "vue3-toastify";
import { getUserTasks, postTasks, updateTask, deleteTask } from "../composables/request";
import { storeToRefs } from "pinia";
import { useTaskStore } from "../stores/task";
const {
    tareas
} = storeToRefs(useTaskStore());

const filtro = ref("");
const displayTaskDialog = ref(false);
const displayDeleteDialog = ref(false);
const tareaSeleccionada = ref(null);
const loading = ref(false);
const submitted = ref(false);
const isEditing = ref(false);
const modalTitle = ref("Nueva Tarea");

const tareaForm = ref({
  id: null,
  title: "",
  description: "",
  completed: false
});

onMounted(async () => {
  await cargarTareas();
});

const cargarTareas = async () => {
  try {
    const response = await getUserTasks();
    tareas.value = response;
  } catch (error) {
    toast.error("Error al cargar las tareas");
    console.error("Error al obtener tareas:", error);
  }
};

// Función para abrir el modal de creación
const abrirModalCreacion = () => {
  isEditing.value = false;
  modalTitle.value = "Nueva Tarea";
  tareaForm.value = { id: null, title: "", description: "", completed: false };
  submitted.value = false;
  displayTaskDialog.value = true;
};

// Función para abrir el modal de edición
const abrirModalEdicion = (tarea) => {
  isEditing.value = true;
  modalTitle.value = "Editar Tarea";
  tareaForm.value = { 
    id: tarea.id,
    title: tarea.title,
    description: tarea.description,
    completed: tarea.completed
  };
  submitted.value = false;
  displayTaskDialog.value = true;
};

// Función para cerrar el diálogo
const cerrarDialogoTarea = () => {
  displayTaskDialog.value = false;
  submitted.value = false;
};

// Función para guardar/actualizar la tarea
const guardarTarea = async () => {
  submitted.value = true;

  if (!tareaForm.value.title) {
    toast.warning("El título es requerido");
    return;
  }

  loading.value = true;

  try {
    const taskData = {
      title: tareaForm.value.title,
      description: tareaForm.value.description,
      completed: tareaForm.value.completed
    };

    if (isEditing.value) {
      await updateTask(tareaForm.value.id, taskData);
      toast.success("Tarea actualizada correctamente");
    } else {
      await postTasks(taskData);
      toast.success("Tarea creada correctamente");
    }

    displayTaskDialog.value = false;
    await cargarTareas(); // Recargar las tareas después de guardar
  } catch (error) {
    const errorMsg = isEditing.value 
      ? "Error al actualizar la tarea" 
      : "Error al crear la tarea";
    toast.error(errorMsg);
    console.error(errorMsg, error);
  } finally {
    loading.value = false;
  }
};

// Función para cambiar el estado de la tarea (completada/pendiente)
const cambiarEstadoTarea = async (tarea) => {
  try {
    const nuevoEstado = !tarea.completed;
    
    const taskData = {
      title: tarea.title,
      description: tarea.description,
      completed: nuevoEstado
    };

    await updateTask(tarea.id, taskData);
    
    const mensaje = nuevoEstado ? 'Tarea marcada como completada' : 'Tarea marcada como pendiente';
    toast.success(mensaje);
    
    await cargarTareas(); // Recargar las tareas después de actualizar
  } catch (error) {
    toast.error("Error al actualizar el estado de la tarea");
    console.error("Error al cambiar estado:", error);
  }
};

// Filtrar tareas según el texto de búsqueda
const tareasFiltradas = computed(() => {
  if (!filtro.value) return tareas.value;
  return tareas.value.filter(
    (tarea) =>
      tarea.title.toLowerCase().includes(filtro.value.toLowerCase()) ||
      (tarea.description && tarea.description.toLowerCase().includes(filtro.value.toLowerCase()))
  );
});

const confirmarEliminar = (tarea) => {
  tareaSeleccionada.value = tarea;
  displayDeleteDialog.value = true;
};

const eliminarTarea = async () => {
  loading.value = true;
  
  try {
    await deleteTask(tareaSeleccionada.value.id);
    toast.success("Tarea eliminada correctamente");
    await cargarTareas(); // Recargar las tareas después de eliminar
  } catch (error) {
    toast.error("Error al eliminar la tarea");
    console.error("Error al eliminar tarea:", error);
  } finally {
    loading.value = false;
    displayDeleteDialog.value = false;
    tareaSeleccionada.value = null;
  }
};
</script>

<style scoped>
.confirmation-content {
  display: flex;
  align-items: center;
}

.field {
  margin-bottom: 1rem;
}
</style>

// react-frontend/src/components/table/TaskTable.tsx
import { useState, useEffect, useRef } from "react";
import { DataTable } from "primereact/datatable";
import { Column } from "primereact/column";
import { Tag } from "primereact/tag";
import { Button } from "primereact/button";
import { InputText } from "primereact/inputtext";
import { FloatLabel } from "primereact/floatlabel";
import { Dialog } from "primereact/dialog";
import { confirmDialog } from "primereact/confirmdialog";
import { useDispatch, useSelector } from "react-redux";
import {
  fetchTasks,
  createTask,
  _updateTask,
  removeTask,
} from "../../store/slices/taskSlice";
import type { AppDispatch, RootState } from "../../store/index";
import { InputTextarea } from "primereact/inputtextarea";
import { showErrorToast, showSuccessToast } from "../../utils/toastUtils";
import { Toast } from "primereact/toast";

interface TareaUI {
  id: number;
  title: string;
  description: string;
  completed: boolean;
  userId: number;
  createdAt: string;
  updatedAt: string;
}

export default function TaskTable() {
  const dispatch = useDispatch<AppDispatch>();
  const { tasks } = useSelector((state: RootState) => state.tasks);

  const [filtro, setFiltro] = useState("");
  const [mostrarModal, setMostrarModal] = useState(false);
  const [tareaSeleccionada, setTareaSeleccionada] = useState<TareaUI | null>(
    null
  );
  const toast = useRef<Toast>(null);
  const [loading, setLoading] = useState<boolean>(false);

  // Cargar tareas al montar el componente
  useEffect(() => {
    dispatch(fetchTasks());
  }, [dispatch]);

  // Función para formatear la fecha
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString();
  };

  // Filtrar tareas por título, descripción o estado
  const tareasFiltradas = tasks.filter((tarea) =>
    [
      tarea.title,
      tarea.description,
      tarea.completed ? "completada" : "pendiente",
    ]
      .join(" ")
      .toLowerCase()
      .includes(filtro.toLowerCase())
  );

  // Cambiar estado pendiente/completada
  const toggleEstado = async (id: number) => {
    const task = tasks.find((t) => t.id === id);
    if (task) {
      try {
        await dispatch(
          _updateTask({
            taskId: id,
            taskData: { completed: !task.completed },
          })
        ).unwrap();
        showSuccessToast(toast, "Tarea actualizada corrrectamente.");
      } catch (error) {
        console.error("Error al cambiar estado:", error);
      }
    }
  };

  // Abrir modal para editar tarea
  const editarTarea = (tarea: TareaUI) => {
    setTareaSeleccionada({ ...tarea }); // crear copia para edición
    setMostrarModal(true);
  };

  // Eliminar tarea con confirmación
  const eliminarTarea = (id: number) => {
    const tarea = tasks.find((t) => t.id === id);
    confirmDialog({
      message: `¿Estás seguro de eliminar la tarea "${tarea?.title}"?`,
      header: "Confirmar eliminación",
      icon: "pi pi-exclamation-triangle",
      acceptLabel: "Sí",
      rejectLabel: "No",
      acceptClassName: "p-button-danger",
      accept: async () => {
        try {
          await dispatch(removeTask(id)).unwrap();
          showSuccessToast(toast, "Tarea eliminada correctamente.");
          dispatch(fetchTasks());
        } catch (error) {
          showErrorToast(toast, "Error al eliminar la tarea");
        }
      },
    });
  };

  // Abrir modal para nueva tarea
  const nuevaTarea = () => {
    setTareaSeleccionada({
      id: 0,
      title: "",
      description: "",
      completed: false,
      userId: 0, // Esto lo debería establecer el backend
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
    setMostrarModal(true);
  };

  // Guardar tarea (crear o actualizar)
  const guardarTarea = async () => {
    if (!tareaSeleccionada) return;

    if (
      !tareaSeleccionada.title.trim() ||
      !tareaSeleccionada.description.trim()
    ) {
      showErrorToast(toast, "Todos los campos son obligatorios.");
      return;
    }

    try {
      setLoading(true);
      if (tareaSeleccionada.id === 0) {
        // Crear nueva tarea
        const taskData = {
          title: tareaSeleccionada.title,
          description: tareaSeleccionada.description,
          completed: tareaSeleccionada.completed || false,
        };

        // Dispatch la acción createTask y espera a que se complete
        await dispatch(createTask(taskData)).unwrap();
        showSuccessToast(toast, "Tarea creada correctamente.");
        setMostrarModal(false);
      } else {
        // Actualizar tarea existente
        const taskData = {
          title: tareaSeleccionada.title,
          description: tareaSeleccionada.description,
          completed: tareaSeleccionada.completed,
        };
        await dispatch(
          _updateTask({
            taskId: tareaSeleccionada.id,
            taskData,
          })
        ).unwrap();
        setTareaSeleccionada(null);
        showSuccessToast(toast, "Tarea actualizada correctamente.");
        setMostrarModal(false);
      }
    } catch (error) {
      console.error("Error al guardar la tarea:", error);
      showErrorToast(toast, "Error al guardar la tarea");
    }
    dispatch(fetchTasks());
    setLoading(false);
  };

  // Template para mostrar el estado
  const estadoTemplate = (task: { completed: boolean }) => (
    <Tag
      value={task.completed ? "Completada" : "Pendiente"}
      severity={task.completed ? "success" : "warning"}
    />
  );

  const accionesTemplate = (rowData: TareaUI) => (
    <div className="d-flex gap-2 justify-content-center">
      <Button
        raised
        icon={rowData.completed === true ? "pi pi-undo" : "pi pi-check"}
        className={`p-button-rounded ${
          rowData.completed === true ? "p-button" : "p-button"
        }`}
        onClick={() => toggleEstado(rowData.id)}
        tooltip={
          rowData.completed === true
            ? "Marcar como pendiente"
            : "Marcar como completada"
        }
        tooltipOptions={{ position: "top" }}
        size="small"
      />
      <Button
        raised
        icon="pi pi-pencil"
        className="p-button-rounded"
        onClick={() => editarTarea(rowData)}
        tooltip="Editar tarea"
        tooltipOptions={{ position: "top" }}
        size="small"
      />
      <Button
        raised
        icon="pi pi-trash"
        className="p-button-rounded"
        onClick={() => eliminarTarea(rowData.id)}
        tooltip="Eliminar tarea"
        tooltipOptions={{ position: "top" }}
        size="small"
      />
    </div>
  );

  const header = (
    <div className="d-flex d-flex-wrap align-items-center justify-content-between gap-2">
      <span className="text-xl text-900 font-bold">
        <i className="pi pi-table mx-2"></i> Listado de tareas
      </span>
    </div>
  );

  const footer = `En total hay ${tasks ? tasks.length : 0} tareas`;

  return (
    <div>
      <Toast ref={toast} />
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h1 className="mb-0"></h1>
        <Button
          label="Crear nueva tarea"
          icon="pi pi-plus"
          className="p-button-primary"
          onClick={nuevaTarea}
          raised
        />
      </div>
      <div className="mb-3 flex justify-content-between align-items-center">
        <FloatLabel>
          <InputText
            id="filtro"
            value={filtro}
            onChange={(e) => setFiltro(e.target.value)}
            className="w-100"
          />
          <label htmlFor="filtro">Buscar tarea...</label>
        </FloatLabel>
      </div>

      <DataTable
        value={tareasFiltradas}
        paginator
        rows={5}
        rowsPerPageOptions={[5, 10, 15, 20]}
        paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"
        currentPageReportTemplate="Mostrando {first} a {last} de {totalRecords} tareas"
        totalRecords={tareasFiltradas.length}
        responsiveLayout="scroll"
        header={header}
        footer={footer}
        stripedRows
        showGridlines
        emptyMessage="No hay tareas."
      >
        <Column field="title" header="Título" sortable />
        <Column field="description" header="Descripción" />
        <Column
          field="createdAt"
          header="Fecha de alta"
          body={(rowData) => formatDate(rowData.createdAt)}
          sortable
        />
        <Column
          field="updatedAt"
          header="Fecha de actualizacón"
          body={(rowData) => formatDate(rowData.createdAt)}
          sortable
        />
        <Column field="estado" header="Estado" body={estadoTemplate} sortable />
        <Column
          header="Acciones"
          body={accionesTemplate}
          style={{ width: "160px" }}
        />
      </DataTable>

      <Dialog
        header={tareaSeleccionada?.id === 0 ? "Nueva Tarea" : "Editar Tarea"}
        visible={mostrarModal}
        modal
        onHide={() => setMostrarModal(false)}
        footer={
          <div className="d-flex justify-content-end gap-2">
            <Button
              label="Cancelar"
              icon="pi pi-times"
              className="p-button-secondary"
              onClick={() => setMostrarModal(false)}
            />
            <Button
              label="Guardar"
              icon="pi pi-check"
              onClick={guardarTarea}
              autoFocus
              loading={loading}
            />
          </div>
        }
      >
        <div className="p-fluid grid mt-4">
          {/* Primera fila - Título */}
          <div className="col-12">
            <FloatLabel className="mt-4">
              <InputText
                id="title"
                value={tareaSeleccionada?.title || ""}
                onChange={(e) =>
                  setTareaSeleccionada((prev) =>
                    prev ? { ...prev, title: e.target.value } : prev
                  )
                }
                className="w-100"
              />
              <label htmlFor="title">Título</label>
            </FloatLabel>
          </div>

          {/* Segunda fila - Descripción */}
          <div className="col-12 mt-3">
            <FloatLabel className="mt-4">
              <InputTextarea
                id="description"
                value={tareaSeleccionada?.description || ""}
                onChange={(e) =>
                  setTareaSeleccionada((prev) =>
                    prev ? { ...prev, description: e.target.value } : prev
                  )
                }
                className="w-100"
                rows={5}
                autoResize
              />
              <label htmlFor="description">Descripción</label>
            </FloatLabel>
          </div>
        </div>
      </Dialog>
    </div>
  );
}
