// react-frontend/src/components/login/RegisterForm.tsx
import { useRef, useState } from "react";
import { InputText } from "primereact/inputtext";
import { Password } from "primereact/password";
import { Button } from "primereact/button";
import { Card } from "primereact/card";
import { FloatLabel } from "primereact/floatlabel";
import { Toast } from "primereact/toast";
import { registerUser } from "../../api/auth"; 
import type { RegisterFormProps } from "../../types/Interfaces";
import { showErrorToast, showSuccessToast } from "../../utils/toastUtils";

export default function RegisterForm({ onRegister, onSwitchToLogin }: RegisterFormProps) {
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [loading, setLoading] = useState<boolean>(false);

  const toast = useRef<Toast>(null);

const handleSubmit = async (e: React.FormEvent) => {
  e.preventDefault();

  if (!fullName || !email || !password || !confirmPassword) {
    showErrorToast(toast, "Todos los campos son obligatorios");
    return;
  }

  if (password !== confirmPassword) {
    showErrorToast(toast, "Las contraseñas no coinciden");
    return;
  }

  try {
    setLoading(true);
    await registerUser(fullName, email, password);
    showSuccessToast(toast, "Cuenta creada exitosamente");
    onRegister(fullName, email, password);
    onSwitchToLogin();
  } catch (error: any) {
    const message = error.response?.data?.message || "Error al registrar usuario";
    showErrorToast(toast, message);
  }
  setLoading(false);
};

  return (
    <div className="d-flex align-items-center justify-content-center min-vh-100 bg-light">
      <Toast ref={toast} />
      <Card style={{ maxWidth: "600px", width: "100%" }}>
        <div className="text-center mb-4">
          <img src="/logosvg.svg" alt="Logo" className="w-50" />
          <h2 className="mt-3">Crear Cuenta</h2>
        </div>

        <form onSubmit={handleSubmit} className="container">
          <div className="row g-3">
            <div className="col-md-6">
              <FloatLabel className="mt-3">
                <InputText
                  id="fullName"
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  className="w-100"
                />
                <label htmlFor="fullName">Nombre de usuario</label>
              </FloatLabel>
            </div>

            <div className="col-md-6">
              <FloatLabel className="mt-3">
                <InputText
                  id="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-100"
                />
                <label htmlFor="email">Correo</label>
              </FloatLabel>
            </div>

            <div className="col-md-6">
              <FloatLabel className="mt-3">
                <Password
                  id="password"
                  toggleMask
                  feedback={false}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-100"
                />
                <label htmlFor="password">Contraseña</label>
              </FloatLabel>
            </div>

            <div className="col-md-6">
              <FloatLabel className="mt-3">
                <Password
                  id="confirmPassword"
                  toggleMask
                  feedback={false}
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  className="w-100"
                />
                <label htmlFor="confirmPassword">Confirmar contraseña</label>
              </FloatLabel>
            </div>

            <div className="col-12 d-grid gap-2 mt-3">
              <Button
                label="Registrarse"
                icon="pi pi-user-plus"
                type="submit"
                className="w-100"
                raised
                loading={loading}
              />
              <Button
                label="Ya tengo cuenta"
                link
                onClick={onSwitchToLogin}
                className="w-100 p-0"
              />
            </div>
          </div>
        </form>
      </Card>
    </div>
  );
}

// vue-frontend/src/components/RegisterForm.vue
<template>
  <div>
    <div
      class="d-flex align-items-center justify-content-center min-vh-100 bg-light"
    >
      <Card style="max-width: 500px; width: 100%">
        <template #title>
          <div class="text-center mb-4">
            <img src="/logosvg.svg" alt="Logo" class="w-50" />
            <h2 class="mt-3">Registro</h2>
          </div>
        </template>

        <template #content>
          <form @submit.prevent="handleSubmit" class="d-flex flex-column gap-3">
            <div class="row">
              <div class="col-6">
                <div class="d-flex-column gap-2">
                  <label for="username">Nombre de usuario</label>
                  <InputText id="username" v-model="username" class="w-100" />
                </div>
              </div>
              <div class="col-6">
                <div class="d-flex-column gap-2">
                  <label for="email">Correo</label>
                  <InputText id="email" v-model="email" class="w-100" />
                </div>
              </div>
              <div class="col-6">
                <div class="d-flex-column gap-2">
                  <label for="password">Contraseña</label>
                  <Password id="password" v-model="password" toggleMask :feedback="false" />
                </div>
              </div>
              <div class="col-6">
                <div class="d-flex-column gap-2">
                  <label for="confirmPassword">Confirmar contraseña</label>
                  <Password
                    id="confirmPassword"
                    v-model="confirmPassword"
                    toggleMask
                    :feedback="false"
                  />
                </div>
              </div>
            </div>

            <Button
              label="Crear cuenta"
              icon="pi pi-user-plus"
              type="submit"
              class="w-100"
              raised
              :loading="loading"
            />
            <Button
              label="Iniciar Sesión"
              link
              @click="onSwitchToLogin"
              class="w-100 p-0"
            />
          </form>
        </template>
      </Card>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import InputText from "primevue/inputtext";
import Password from "primevue/password";
import Button from "primevue/button";
import Card from "primevue/card";
import { toast } from "vue3-toastify";
import { registerUser } from "../composables/request";

const router = useRouter();

const username = ref("");
const email = ref("");
const password = ref("");
const confirmPassword = ref("");
const loading = ref(false);

const onSwitchToLogin = () => {
  router.push("/");
};

const isValid = () => {
  if (!username.value.trim()) {
    toast.warn("El nombre de usuario es requerido");
    return false;
  }
  
  if (!email.value.trim()) {
    toast.warn("El correo electrónico es requerido");
    return false;
  }
  
  if (!isEmailValid(email.value)) {
    toast.warn("Por favor ingrese un correo electrónico válido");
    return false;
  }
  
  if (!password.value.trim()) {
    toast.warn("La contraseña es requerida");
    return false;
  }
  
  if (password.value !== confirmPassword.value) {
    toast.warn("Las contraseñas no coinciden");
    return false;
  }
  
  return true;
};

const isEmailValid = (email) => {
  const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return re.test(email);
};

const handleSubmit = async () => {
  if (!isValid()) return;

  try {
    loading.value = true;
    const response = await registerUser(
      username.value,
      email.value,
      password.value
    );
    
    if (response) {
      toast.success("Registro exitoso. Por favor inicie sesión.");
      router.push("/");
    }
  } catch (error) {
    console.error("Error en registro:", error);
    toast.error(error.response?.data?.message || "Error al registrar usuario");
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
/* Estilos personalizados */
.bg-light {
  background-color: #f8f9fa;
}
.min-vh-100 {
  min-height: 100vh;
}
.d-flex {
  display: flex;
}
.align-items-center {
  align-items: center;
}
.justify-content-center {
  justify-content: center;
}
.gap-3 {
  gap: 1rem;
}
.w-50 {
  width: 50%;
}
.w-100 {
  width: 100%;
}
.mt-3 {
  margin-top: 1rem;
}
.mb-4 {
  margin-bottom: 1.5rem;
}
.p-0 {
  padding: 0;
}
.text-center {
  text-align: center;
}
</style>
